// <auto-generated />
namespace PhotoStore.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fotoeprodutounidosnoitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fotoeprodutounidosnoitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201802261737297_foto e produto unidos no item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
